# Generated by Django 5.2.1 on 2025-08-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': {('send_private_email', 'Can send private email to user by the button.')}},
        ),
    ]
